//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.6-2.1.6-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.25 at 10:08:28 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.globalcompany.example.com/ns/OrderBookingService/rules", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.globalcompany.ns.orderbookingservice.rules;
