<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="../xsd/EDI_X12/4010/850/850_Def/850.xsd"/>
      <rootElement name="Transaction-850" namespace="urn:oracle:integration:b2b:X12/4010/850"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../services/oracle/fodemo/storefront/store/service/common/serviceinterface/StoreFrontService.wsdl"/>
      <rootElement name="createOrderInfoVOSDO" namespace="www.globalcompany.example.com/types/"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.0.0(build 081120.0800.2199) AT [THU NOV 20 21:57:39 PST 2008]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xpath20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:types="www.globalcompany.example.com/types/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:errors="http://xmlns.oracle.com/adf/svc/errors/"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns2="commonj.sdo/xml"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns3="http://xmlns.oracle.com/adf/svc/types/"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="www.globalcompany.example.com"
                xmlns:ns4="commonj.sdo/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.GetRequestHeaderExtnFunction"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="urn:oracle:integration:b2b:X12/4010/850"
                xmlns:ns5="/oracle/fodemo/storefront/store/queries/common/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="commonj.sdo"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns0 xsd types soap wsdl errors ns2 ns3 tns ns4 ns5 ns1 bpws xpath20 ora socket oraext dvm hwf mhdr med ids xdk xref ldap">
  <xsl:template match="/">
    <types:createOrderInfoVOSDO>
      <types:orderInfoVO1>
          <ns5:OrderId>
            <xsl:value-of select="/ns0:Transaction-850/ns0:Segment-BEG/ns0:Element-324"/>
          </ns5:OrderId>
          <ns5:OrderDate>
            <xsl:value-of select="/ns0:Transaction-850/ns0:Segment-BEG/ns0:Element-373"/>
          </ns5:OrderDate>
          <ns5:OrderTotal>
            <xsl:value-of select="/ns0:Transaction-850/ns0:Loop-CTT/ns0:Segment-AMT/ns0:Element-782"/>
          </ns5:OrderTotal>
          <ns5:CustomerId>
            <xsl:text disable-output-escaping="no">10</xsl:text>
          </ns5:CustomerId>
          <ns5:AccountNumber>
            <xsl:text disable-output-escaping="no">41</xsl:text>
          </ns5:AccountNumber>
          <ns5:CardTypeCode>
            <xsl:text disable-output-escaping="no">AMEX</xsl:text>
          </ns5:CardTypeCode>
          <xsl:for-each select="/ns0:Transaction-850/ns0:Loop-PO1">
            <ns5:OrderItemsInfoVO>
              <ns5:OrderId>
                <xsl:value-of select="../ns0:Segment-BEG/ns0:Element-324"/>
              </ns5:OrderId>
              <ns5:LineItemId>
                <xsl:value-of select="ns0:Segment-PO1/ns0:Element-350"/>
              </ns5:LineItemId>
              <ns5:ProductId>
                <xsl:value-of select="ns0:Segment-PO1/ns0:Element-234"/>
              </ns5:ProductId>
              <ns5:Quantity>
                <xsl:value-of select="ns0:Segment-PO1/ns0:Element-330"/>
              </ns5:Quantity>
              <ns5:UnitPrice>
                <xsl:value-of select="ns0:Segment-PO1/ns0:Element-212"/>
              </ns5:UnitPrice>
              <ns5:ProductId1>
                <xsl:value-of select="ns0:Segment-PO1/ns0:Element-234"/>
              </ns5:ProductId1>
            </ns5:OrderItemsInfoVO>
          </xsl:for-each>
      </types:orderInfoVO1>
    </types:createOrderInfoVOSDO>
  </xsl:template>
</xsl:stylesheet>
